nuxeo/nuxeo-template-rendering

- nuxeo-template-rendering-api/src/main/java/org/nuxeo/template/api/adapters/TemplateSourceDocument.java
- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/adapters/source/TemplateSourceDocumentAdapterImpl.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/TestAdapters.java
- nuxeo-template-rendering-web/src/main/java/org/nuxeo/template/web/BaseTemplateAction.java
- nuxeo-template-rendering-web/src/main/java/org/nuxeo/template/web/TemplateBasedActionBean.java
- nuxeo-template-rendering-web/src/main/java/org/nuxeo/template/web/TemplatesActionBean.java
- nuxeo-template-rendering-web/src/main/resources/OSGI-INF/l10n/messages_en_US.properties
PR created from https://qa.nuxeo.org/jenkins/job/ondemand-testandpush-kleturc-7.10/7/
> fix-NXP-18968-parameter-with-same-name-template-rendering-7.10

- nuxeo-template-rendering-web/src/main/java/org/nuxeo/template/web/TemplateBasedActionBean.java
- nuxeo-template-rendering-web/src/main/java/org/nuxeo/template/web/TemplatesActionBean.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-ataillefer-7.10/5/
> fix-NXP-18969-template-params-inconsistent-redirection-7.10

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/listeners/TemplateInitListener.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-ataillefer-7.10/6/
> fix-NXP-18967-NPE-template-no-blob-7.10

- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/pub/tests/TestRenditionPublication.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger2/5/
> fix-NXP-20397-filter-rendition-definition

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/context/SimpleSchemaWrapper.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/89/
> feature-NXP-19654-deprecated-DocumentPart

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/odt/OOoArchiveModifier.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/TestFreemarkerVariableExractor.java
- nuxeo-template-rendering-sandbox/src/main/java/org/nuxeo/template/processors/docx/WordXMLRawTemplateProcessor.java
- nuxeo-template-rendering-xdocreport/src/main/java/org/nuxeo/template/processors/xdocreport/XDocReportBindingResolver.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/110/
> task-NXP-21378-deprecate-methods-of-fileutils

- nuxeo-template-rendering-web/src/main/java/org/nuxeo/template/web/TemplateBasedActionBean.java
- nuxeo-template-rendering-xdocreport/src/main/java/org/nuxeo/template/xdocreport/jaxrs/NuxeoLargeBinaryDataMessageWriter.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-8.10-bis/5/
> fix-NXP-21294-revert-automation-backport-8.10

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/adapters/doc/TemplateBasedDocumentAdapterImpl.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-slacoin/136/
> fix-NXP-21508-automation-chain-parameters

- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-template-rendering/nuxeo-render-template-button.html
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-gbarata-8.10/11/
> fix-NXP-22033-firefox-ie11-8.10

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/XMLSerializer.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/TestXMLSerialization.java
- nuxeo-template-rendering-sandbox/src/main/java/org/nuxeo/template/processors/docx/WordXMLRawTemplateProcessor.java
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-template-rendering/nuxeo-template-param-editor.html
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/160/
> fix-NXP-22071-date-formatting

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/XMLSerializer.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/TestXMLSerialization.java
- nuxeo-template-rendering-sandbox/src/main/java/org/nuxeo/template/processors/docx/WordXMLRawTemplateProcessor.java
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-template-rendering/nuxeo-template-param-editor.html
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-8.10/15/
> fix-NXP-22071-date-formatting-8.10

- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/BaseConverterTest.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/TestOOoConvert.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/TestService.java
- nuxeo-template-rendering-samples/src/test/java/org/nuxeo/template/samples/tests/TestImportedModelRendering.java
- nuxeo-template-rendering-xdocreport/src/test/java/org/nuxeo/ecm/platform/template/tests/TestFreemarkerVariableExractor.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-bstefanescu-master/13/
> feature-NXP-19326-runtime-evols

- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/pub/tests/TestRenditionPublication.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/163/
> feature-NXP-22920-bulkDownload

- nuxeo-template-rendering-samples-jsf/ReadMe.md
- nuxeo-template-rendering-samples-jsf/pom.xml
- nuxeo-template-rendering-samples-jsf/src/main/resources/META-INF/MANIFEST.MF
- nuxeo-template-rendering-samples-jsf/src/main/resources/OSGI-INF/deployment-fragment.xml
- nuxeo-template-rendering-samples-jsf/src/main/resources/OSGI-INF/extensions.xml
- nuxeo-template-rendering-samples-jsf/src/main/resources/web/nuxeo.war/layouts/template-module-demo_layout_template.xhtml
- nuxeo-template-rendering-samples-jsf/src/main/resources/web/nuxeo.war/layouts/template-module-demo_tab_layout_template.xhtml
- nuxeo-template-rendering-samples-jsf/src/main/resources/web/nuxeo.war/studio_tabs/studio_tab_nxtrGoToWebUITab.xhtml
- pom.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-master/136/
> fix-NXP-23547-template-rendering-samples-jsf

- nuxeo-template-rendering-jsf/src/main/resources/web/nuxeo.war/incl/tabs/templatebased_tab.xhtml
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-8.10/84/
> 8.10-HF/fix-NXP-22882-template-title

- nuxeo-template-rendering-jsf/src/main/resources/web/nuxeo.war/incl/tabs/templatebased_tab.xhtml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger/190/
> fix-NXP-22882-template-title

- nuxeo-template-rendering-web/src/main/resources/web/nuxeo.war/incl/tabs/templatebased_tab.xhtml
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-7.10/40/
> 7.10-HF/fix-NXP-22882-template-title

- nuxeo-template-rendering-jaxrs/pom.xml
- nuxeo-template-rendering-xdocreport/pom.xml
- nuxeo-template-rendering-xdocreport/src/main/java/org/nuxeo/template/xdocreport/jaxrs/JSONHelper.java
- nuxeo-template-rendering-xdocreport/src/main/java/org/nuxeo/template/xdocreport/jaxrs/XDocReportResourceService.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/310/
> cleanup-NXP-24081-remove-jackson1

- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/pub/tests/TestRenditionPublication.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/311/
> cleanup-NXP-24089-CloseableCoreSession

- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/document/templatesource/nuxeo-templatesource-create-layout.html
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/document/templatesource/nuxeo-templatesource-edit-layout.html
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/document/templatesource/nuxeo-templatesource-import-layout.html
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/document/templatesource/nuxeo-templatesource-metadata-layout.html
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/document/templatesource/nuxeo-templatesource-view-layout.html
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-template-rendering/nuxeo-render-template-button.html
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-template-rendering/nuxeo-template-rendering-page.html
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-template-rendering/nuxeo-template-rendering.html
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-ajusto/2/
> fix-NXP-23964-layout-styles-9.10

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/processors/AbstractBindingResolver.java
- nuxeo-template-rendering-sandbox/src/main/java/org/nuxeo/template/processors/docx/WordXMLRawTemplateProcessor.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/315/
> cleanup-NXP-24092-code-quality

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/service/TemplateProcessorComponent.java
- nuxeo-template-rendering-jsf/src/main/java/org/nuxeo/template/jsf/TemplateBasedActionBean.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/316/
> cleanup-NXP-24092-code-quality-2

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/XMLSerializer.java
- nuxeo-template-rendering-xdocreport/src/test/java/org/nuxeo/ecm/platform/template/tests/TestXDocReportDOCXProcessing.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/318/
> cleanup-NXP-24092-code-quality-3

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/odt/OOoArchiveModifier.java
- nuxeo-template-rendering-xdocreport/src/main/java/org/nuxeo/template/xdocreport/jaxrs/JSONHelper.java
- nuxeo-template-rendering-xdocreport/src/main/java/org/nuxeo/template/xdocreport/jaxrs/XDocReportResourceService.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/322/
> cleanup-NXP-24092-code-quality-5

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/service/TemplateProcessorComponent.java
- nuxeo-template-rendering-core/src/main/resources/OSGI-INF/pageprovider-contrib.xml
- nuxeo-template-rendering-samples/src/main/java/org/nuxeo/template/samples/importer/ModelImporter.java
- nuxeo-template-rendering-web-ui/src/main/resources/OSGI-INF/operations-contrib.xml
- nuxeo-template-rendering-xdocreport/src/main/java/org/nuxeo/template/xdocreport/jaxrs/AbstractResourceService.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/326/
> feature-NXP-24033-nxql-is-trashed

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/listeners/TemplateInitListener.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/378/
> feature-NXP-24032-doc-model-trashed-api

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/odt/OOoArchiveModifier.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/TestFreemarkerVariableExractor.java
- nuxeo-template-rendering-sandbox/src/main/java/org/nuxeo/template/processors/docx/WordXMLRawTemplateProcessor.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/382/
> task-NXP-24371-remove-dreprecated-usage-commons-lang3

- nuxeo-template-rendering-jsf/src/main/resources/OSGI-INF/layouts-contrib.xml
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-9.10/6/
> fix-NXP-24479-blob-filename-fallback-9.10

- nuxeo-template-rendering-jsf/src/main/resources/OSGI-INF/layouts-contrib.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-master/150/
> fix-NXP-24479-blob-filename-fallback

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/service/TemplateProcessorComponent.java
- nuxeo-template-rendering-core/src/main/resources/OSGI-INF/pageprovider-contrib.xml
- nuxeo-template-rendering-samples-jsf/src/main/resources/OSGI-INF/extensions.xml
- nuxeo-template-rendering-samples/src/main/java/org/nuxeo/template/samples/importer/ModelImporter.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/356/
> cleanup-NXP-24486-ischeckedinversion

- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/BaseConverterTest.java
- nuxeo-template-rendering-xdocreport/src/test/java/org/nuxeo/ecm/platform/template/tests/TestODTProcessingWithConverter.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume-4/7/
> feature-NXP-25655-remove-jodconverter-ooomanager

- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/pub/tests/TestRenditionPublication.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier2/10/
> cleanup-NXP-25661-cleanup-deploys

- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-template-rendering/nuxeo-delete-template-button.html
- nuxeo-template-rendering-web-ui/src/main/resources/web/nuxeo.war/ui/nuxeo-template-rendering/nuxeo-render-template-button.html
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-gbarata/108/
> feature-NXP-25146-add-labels-to-actions

- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/TestTemplateSourceTypeBindings.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-2/128/
> fix-NXP-25761-trash-migration

- nuxeo-template-rendering-samples-jsf/src/main/resources/OSGI-INF/extensions.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/535/
> fix-NXP-25983-replace-remaining-deleted-state

- nuxeo-template-rendering-core/src/main/resources/OSGI-INF/convert-service-contrib.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger/300/
> fix-NXP-26306-libreoffice

- nuxeo-template-rendering-core/src/main/resources/OSGI-INF/convert-service-contrib.xml
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-9.10/48/
> 9.10-HF/fix-NXP-26306-libreoffice

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/adapters/doc/TemplateBasedDocumentAdapterImpl.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/pub/tests/TestRenditionPublication.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fdavid-master/567/
> fix-NXP-24953-documentnotfoud-deleted-template

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/adapters/doc/TemplateBasedDocumentAdapterImpl.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/pub/tests/TestRenditionPublication.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fdavid-9.10/41/
> fix-NXP-24953-documentnotfound-deleted-template-9.10

- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/service/TemplateMappingFetcher.java
- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/service/TemplateProcessorComponent.java
- nuxeo-template-rendering-jaxrs/src/main/java/org/nuxeo/template/jaxrs/ResourceService.java
- nuxeo-template-rendering-jaxrs/src/main/java/org/nuxeo/template/jaxrs/TemplateBasedResource.java
- nuxeo-template-rendering-jaxrs/src/main/java/org/nuxeo/template/jaxrs/TemplateResource.java
- nuxeo-template-rendering-jaxrs/src/main/java/org/nuxeo/template/jaxrs/context/JAXRSExtensions.java
- nuxeo-template-rendering-samples/src/test/java/org/nuxeo/template/samples/tests/TestImportModel.java
- nuxeo-template-rendering-samples/src/test/java/org/nuxeo/template/samples/tests/TestImportModelViaContentTemplate.java
- nuxeo-template-rendering-xdocreport/src/main/java/org/nuxeo/template/xdocreport/jaxrs/AbstractResourceService.java
- nuxeo-template-rendering-xdocreport/src/main/java/org/nuxeo/template/xdocreport/jaxrs/ResourceService.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier/240/
> NXP-26194-remove-stringbuffer

- nuxeo-template-rendering-api/src/main/java/org/nuxeo/template/api/TemplateInput.java
- nuxeo-template-rendering-api/src/main/java/org/nuxeo/template/api/descriptor/ContextExtensionFactoryDescriptor.java
- nuxeo-template-rendering-api/src/main/java/org/nuxeo/template/api/descriptor/TemplateProcessorDescriptor.java
- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/XMLSerializer.java
- nuxeo-template-rendering-core/src/main/java/org/nuxeo/template/processors/AbstractBindingResolver.java
- nuxeo-template-rendering-core/src/test/java/org/nuxeo/ecm/platform/template/tests/TestXMLSerialization.java
- nuxeo-template-rendering-jod/src/main/java/org/nuxeo/template/processors/jod/JODReportTemplateProcessor.java
- nuxeo-template-rendering-jxls/src/test/java/org/nuxeo/template/processors/tests/SimpleTemplateDocTestCase.java
- nuxeo-template-rendering-sandbox/src/test/java/org/nuxeo/template/processors/test/TestWordXMLRawProcessing.java
- nuxeo-template-rendering-xdocreport/src/test/java/org/nuxeo/ecm/platform/template/tests/SimpleTemplateDocTestCase.java
Not created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-3/27/ but succeed into it
> NXP-24952: Fix new java 11 warnings

- nuxeo-template-rendering-core/pom.xml
- nuxeo-template-rendering-jaxrs/pom.xml
- nuxeo-template-rendering-jod/pom.xml
- nuxeo-template-rendering-jsf/pom.xml
- nuxeo-template-rendering-sandbox/pom.xml
- nuxeo-template-rendering-xdocreport/pom.xml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-pierregautier/256/
> NXP-27075-j11

- nuxeo-template-rendering-web-ui/src/main/resources/OSGI-INF/operations-contrib.xml
Reverts nuxeo/nuxeo-template-rendering#76
> Revert "NXP-25058: add parameter to query to only show the last template version (Backport 10.10)"
